[package]
name = "rust-node"
version = "0.1.0"
authors = ["Jacob Jewell <jacobjewell@eflexsystems.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "rust_node"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.23"

[dependencies]
neon = "0.1.23"
